# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('firstname', models.CharField(max_length=50, verbose_name='FirstName')),
                ('lastname', models.CharField(blank=True, max_length=50, null=True, verbose_name='LastName')),
                ('url', models.CharField(blank=True, max_length=120, null=True, verbose_name='Url')),
                ('cancel', models.BooleanField(default=False, verbose_name='Cancel')),
                ('customer_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='Address')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_unit.BusinessUnit', verbose_name='Business Unit')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Business Unit',
                'verbose_name_plural': 'Business Units',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Business Unit Type',
                'verbose_name_plural': 'Business Unit Types',
            },
        ),
        migrations.AddField(
            model_name='businessunit',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_unit.BusinessUnitType', verbose_name='Type'),
        ),
    ]
