# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=40, null=True, verbose_name='program')),
                ('task', models.CharField(blank=True, max_length=120, verbose_name='task')),
                ('is_program_task', models.BooleanField(default=False, verbose_name='program task status')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('time_spent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='time spent')),
                ('is_rework', models.BooleanField(default=False, verbose_name='rework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TaskTrackingEntry',
                'verbose_name_plural': 'TaskTrackingEntries',
            },
        ),
    ]
