# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCheckList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(choices=[(b'Mr', 'Mr'), (b'Ms', 'Ms'), (b'Mrs', 'Mrs'), (b'Dr', 'Dr')], max_length=3, null=True, verbose_name='salutation')),
                ('fathers_name', models.CharField(blank=True, max_length=56, null=True, verbose_name='Fathers Name')),
                ('email_address_official', models.EmailField(blank=True, max_length=56, null=True, verbose_name='Email Address (Personal)')),
                ('code', models.CharField(blank=True, max_length=8, null=True, verbose_name='code')),
                ('type', models.CharField(blank=True, choices=[(b'E', 'Permanent'), (b'C', 'Contract'), (b'T', 'Trainee'), (b'TP', 'Temporary'), (b'CC', 'Customer contact')], max_length=2, null=True, verbose_name='type')),
                ('division', models.CharField(blank=True, choices=[(b'TECHNICAL', 'Technical'), (b'ADMINISTRATION', 'Administration')], max_length=20, null=True, verbose_name='Division')),
                ('designation', models.CharField(blank=True, max_length=128, null=True, verbose_name='designation')),
                ('gender', models.CharField(blank=True, choices=[(b'M', 'Male'), (b'F', 'Female')], max_length=1, null=True, verbose_name='gender')),
                ('confirmation_status', models.CharField(choices=[(b'CONFIRMED', 'Confirmed'), (b'ONPROBATION', 'On Probation')], max_length=15, verbose_name='confirmation status')),
                ('date_of_confirmation', models.DateField(blank=True, null=True, verbose_name='date of confirmation')),
                ('probation_period', models.CharField(blank=True, choices=[(b'1', '1 Month'), (b'2', '2 Months'), (b'3', '3 Months'), (b'4', '4 Months'), (b'5', '5 Months'), (b'6', '6 Months'), (b'7', '7 Months'), (b'8', '8 Months'), (b'9', '9 Months'), (b'10', '10 Months'), (b'11', '11 Months'), (b'12', '12 Months')], max_length=10, null=True, verbose_name='probation period(in Months)')),
                ('probation_end_date', models.CharField(blank=True, max_length=11, null=True, verbose_name='probation end date')),
                ('blood_group', models.CharField(blank=True, choices=[(b'O+', 'O+'), (b'O-', 'O-'), (b'A+', 'A+'), (b'A-', 'A-'), (b'B+', 'B+'), (b'B-', 'B-'), (b'A1+', 'A1+'), (b'AB+', 'AB+'), (b'AB-', 'AB-')], max_length=3, null=True, verbose_name='blood group')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('date_of_joining', models.DateField(blank=True, null=True, verbose_name='date of joining')),
                ('date_of_resignation', models.DateField(blank=True, null=True, verbose_name='Date of resignation')),
                ('date_of_relieving', models.DateField(blank=True, null=True, verbose_name='Date of relieving')),
                ('phone_office', models.CharField(blank=True, max_length=20, null=True, verbose_name='office telephone number')),
                ('phone_office_extension', models.IntegerField(blank=True, null=True, verbose_name='office telephone extension')),
                ('phone_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='mobile number')),
                ('phone_residence', models.CharField(blank=True, max_length=20, null=True, verbose_name='residence phone number')),
                ('emergency_contact', models.CharField(blank=True, max_length=56, null=True, verbose_name=b'emergency contact')),
                ('phone_emergency1', models.CharField(blank=True, max_length=20, null=True, verbose_name='emergency telephone number 1')),
                ('phone_emergency2', models.CharField(blank=True, max_length=20, null=True, verbose_name='emergency telephone number 2')),
                ('bank_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Bank Name / Branch')),
                ('bank_acc_no', models.CharField(blank=True, max_length=24, null=True, verbose_name='Bank account number')),
                ('pan_no', models.CharField(blank=True, max_length=16, null=True, verbose_name='PAN number')),
                ('pf_no', models.CharField(blank=True, max_length=16, null=True, verbose_name='PF number')),
                ('passport_no', models.CharField(blank=True, max_length=16, null=True, verbose_name='PUserProfileassport number')),
                ('passport_validity', models.DateField(blank=True, null=True, verbose_name='passport validity')),
                ('hide_phone_number', models.BooleanField(default=False, help_text='Your personal phone number will not be listed.', verbose_name='Dont Show phone number in Address Book')),
                ('comments', models.TextField(blank=True, max_length=10, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('document_check_list_others', models.CharField(blank=True, max_length=100, null=True)),
                ('users_image', models.ImageField(blank=True, max_length=300, null=True, upload_to=b'user_images/')),
                ('customer_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='customer_code')),
                ('reporting_senior', models.CharField(blank=True, max_length=8, null=True, verbose_name='Reporting_senior')),
                ('address_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_userprofile_contact_address', to='address.Address', verbose_name='contact address')),
                ('address_permanent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_userprofile_permanent_address', to='address.Address', verbose_name='permanent address')),
                ('business_unit', models.ManyToManyField(to='business_unit.BusinessUnit', verbose_name='business unit')),
                ('document_check_list', models.ManyToManyField(blank=True, to='users.DocumentCheckList', verbose_name='document check list')),
                ('reporting_senior_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_userprofile_reporting_senior_name', to=settings.AUTH_USER_MODEL, verbose_name='reporting_senior_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_userprofile_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='userType',
            fields=[
                ('userType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
