# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Invoice Term',
                'verbose_name_plural': 'Invoice Terms',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='milestone')),
                ('percentage', models.CharField(blank=True, max_length=10, null=True, verbose_name='percentage')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Invoice Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Invoice End Date')),
                ('category', models.CharField(choices=[(b'invoice', b'invoice'), (b'engineering', b'engineering')], default=b'invoice', max_length=16)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('cancel', models.BooleanField(default=False)),
                ('invoice_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='milestone.InvoiceTerms', verbose_name='Invoice Terms')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
            },
        ),
    ]
