# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontact',
            name='telephone',
        ),
    ]
