# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('fileUploaded', models.ImageField(max_length=300, upload_to=b'all files')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryTags',
            fields=[
                ('repositoryTagID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('sequenceNo', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='repositoryTag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.RepositoryTags'),
        ),
    ]
