# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0005_clientvisitreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientVisitReport',
        ),
    ]
