# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0007_clientvisitreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='comments',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
