# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0015_auto_20171218_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='project_name',
            field=models.CharField(max_length=200),
        ),
    ]
