# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0016_auto_20171218_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project name'),
        ),
    ]
