# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-18 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0021_auto_20171218_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_visit_report_clientvisitreport_client_name', to='customer.Customer', verbose_name='client name'),
        ),
    ]
