# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0024_auto_20171219_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_visit_report_clientvisitreport_customer', to='projects.Project', verbose_name='Client Details'),
        ),
    ]
