# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0029_auto_20171220_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.Customer', verbose_name='client name'),
        ),
    ]
