# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_visit_report', '0030_auto_20171220_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientvisitreport',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='clientvisitreport',
            name='reporting_senior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Request To'),
        ),
        migrations.AlterField(
            model_name='clientvisitreport',
            name='client_name',
            field=models.CharField(max_length=200),
        ),
    ]
