# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0033_auto_20171221_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='reporting_senior_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='reporting_senior_name'),
        ),
    ]
