# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0034_auto_20171221_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisitreport',
            name='reporting_senior',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Reporting_senior'),
        ),
        migrations.AlterField(
            model_name='clientvisitreport',
            name='reporting_senior_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_visit_report_clientvisitreport_reporting_senior_name', to=settings.AUTH_USER_MODEL, verbose_name='reporting_senior_name'),
        ),
    ]
