# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0037_auto_20171222_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientvisitreport',
            options={'verbose_name_plural': 'clientvisitreports'},
        ),
        migrations.AlterField(
            model_name='clientvisitreport',
            name='client_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='Client Details'),
        ),
        migrations.AlterField(
            model_name='clientvisitreport',
            name='project_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='clientvisitreport',
            name='reporting_senior_name',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_visit_report_clientvisitreport_reporting_senior_name', to=settings.AUTH_USER_MODEL, verbose_name='reporting_senior_name'),
        ),
    ]
