# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0039_auto_20180106_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisitreport',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
