# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0040_clientvisitreport_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='arrival_time',
            field=models.TimeField(null=True, verbose_name='%H:%M:%S'),
        ),
    ]
