# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-17 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0042_auto_20180115_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientvisitreport',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
