# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0043_auto_20180117_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisitreport',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
