# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-19 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0044_clientvisitreport_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisitreport',
            name='reason_for_reject',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
