# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0047_auto_20180122_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientvisitreport',
            name='reason_for_reject',
        ),
        migrations.AlterField(
            model_name='clientvisitreport',
            name='date_of_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
