# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-26 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0053_clientvisitreport_reason_for_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisitreport',
            name='arrival_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
