# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-26 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0055_auto_20180126_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='arrival_date',
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
    ]
