# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-26 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0056_auto_20180126_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='arrival_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
