# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-26 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0058_auto_20180126_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientvisitreport',
            name='arrival_date',
        ),
    ]
