# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-26 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_visit_report', '0059_remove_clientvisitreport_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientvisitreport',
            name='date_of_approval',
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
    ]
