# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvr',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='cvr',
            name='departure_time',
        ),
    ]
