# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(blank=True, max_length=120, null=True)),
                ('users', models.CharField(blank=True, max_length=120, null=True)),
                ('screen', models.CharField(blank=True, max_length=50, null=True)),
                ('actionPerformed', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(blank=True, max_length=120, null=True)),
                ('users', models.CharField(blank=True, max_length=120, null=True)),
                ('screen', models.CharField(blank=True, max_length=50, null=True)),
                ('actionPerformed', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(blank=True, max_length=120, null=True)),
                ('users', models.CharField(blank=True, max_length=120, null=True)),
                ('screen', models.CharField(blank=True, max_length=50, null=True)),
                ('actionPerformed', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(blank=True, max_length=120, null=True)),
                ('users', models.CharField(blank=True, max_length=120, null=True)),
                ('screen', models.CharField(blank=True, max_length=50, null=True)),
                ('actionPerformed', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
