# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 22:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NonProjectTask',
            fields=[
                ('non_project_taskID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('plannedStartDate', models.DateField(blank=True, null=True)),
                ('plannedEndDate', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancel', models.BooleanField(default=b'False')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('taskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Type')),
            ],
        ),
        migrations.CreateModel(
            name='NonProjectTaskAssignees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualstartDate', models.DateField(blank=True, null=True)),
                ('actualendDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default=b'Incomplete', max_length=50)),
                ('non_project_taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_project_task.NonProjectTask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Non project Task Assignee',
                'verbose_name_plural': 'Non Project Task Assignees',
            },
        ),
    ]
